FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Pre-install GCP credentials
RUN pip install google-auth

COPY backend/ .

ENV PORT=8080
ENV GCP_PROJECT=rexium-nutrisnap
ENV GCP_LOCATION=us-central1

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
